[package]
name = "realtime_voice_translator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.52", features = ["full"] }
tokio-tungstenite = { version = "0.29", features = ["native-tls"] }
futures-util = "0.3"
cpal = "0.18"
rodio = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22" # Для упаковки PCM-байтов в JSON-текст вебсокета
http = "1.4"
